name: Build

on:
  push:
  pull_request:
  release:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "Install"
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cmake make libglu1-mesa-dev libglew-dev libsdl2-dev libsdl2-ttf-dev libtbb-dev libassimp-dev ccache gcc-11 g++-11
        version: 1.0
    - name: "Use ccache"
      uses: hendrikmuhs/ccache-action@v1.2
    - name: "CMake build"
      uses: actions/cache@v3
      with:
        key: cmake-dependencies
        path: |
          build/_deps
    - name: "Build"
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -B build/ .
        ln -s ../mods mods
        cd build
        cmake --build . -- -j$(nproc)
        cd ..
      env:
        CC:   gcc-11
        CXX:  g++-11
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: lukka/get-cmake@latest
    - name: Dump the content of $RUNNER_TEMP
      run: find $RUNNER_TEMP
      shell: bash
    - name: Dump the content of $RUNNER_WORKSPACE
      run: find $RUNNER_WORKSPACE
      shell: bash
    - uses: lukka/run-vcpkg@v10
      id: runvcpkg
      with:
        # This specifies the location of vcpkg, where it is going to be restored from cache, or create from scratch.
        vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
        # The Git commit id of vcpkg to be checked out. This is only needed because we are not using a submodule.
        vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
        # The vcpkg.json file, which will be part of cache key computation.
        vcpkgJsonGlob: '**/vcpkg.json'
    - uses: ilammy/msvc-dev-cmd@v1
    - name: "Make symbolic links"
      run: |
        mkdir builds
        cd builds
        mkdir msbuild-vcpkg
        cd msbuild-vcpkg
        cp -r ../../mods .
        cd ../../
    - name: Run CMake with vcpkg.json manifest
      uses: lukka/run-cmake@v10
      with:
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        configurePreset: msbuild-vcpkg
        buildPreset: msbuild-vcpkg
