name: Build

on:
  push:
  pull_request:
  release:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Install"
      run: |
        sudo apt install -y cmake make xorg-dev libglu1-mesa-dev
    - name: "Build"
      run: |
        ./quick_build.sh
