name: Build

on:
  push:
  pull_request:
  release:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: "Install"
      run: |
        sudo apt install -y cmake make libglu1-mesa-dev libglew-dev libsdl2-dev libsdl2-ttf-dev libtbb-dev
    - name: "CMake build"
      uses: actions/cache@v3
      with:
        key: cmake-dependencies
        path: |
          build/_deps
    - name: "Build"
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release -DE3D_BACKEND_OPENGL=1 -B build/ .
        ln -s ../mods mods
        cd build
        cmake --build . -- -j$(nproc)
        cd ..
